<?php

namespace Domain\Repositories;

use Domain\Models\Person;
use Domain\Models\PersonDetailed;
use Domain\Models\Link;
use Domain\Models\Message;

interface LocalPersonRepository
{
    /**
     * Find as many as possible Redflags depending of args given to the function.
     * If no args are given, we may return nothing.
     * 
     * @param string|null $firstname
     * @param string|null $lastName
     * @param string|null $zoneName
     * @return Person[]
     */
    function findMany(string|null $firstname = null, string|null $lastname = null, string|null $jobname = null, string|null $zonename = null): array;

    /**
     * Find a unique RedFlag given the id.
     *  
     * @param string $id
     * @return PersonDetailed
     */
    function findUnique(string $id): PersonDetailed|null;

    /**
     * Create a new person entry in local database.
     * 
     * @param PersonDetailed $personDetailed Data of the person entry that will be added to database.
     * The id is generated by server. The id from $personDetailed wont be taken. You can simply put an empty string.
     * If a person that seem exactly like the one given on params exists, then we just return this one.
     * @return PersonDetailed The detailed person created with unique ID.
     */
    function createOne(Person $person): void;

    /**
     * Add a link (resource, article) about a person in database.
     * 
     * @param string $id This database use uuid as ID.
     * @param Link $link The new message to add to the person.
     * @return PersonDetailed The detailed person updated with new message.
     */
    function addLink(string $id, Link $link): void;
}
